# Created with YamlCreate.ps1 v2.2.8 $debug=NVS1.CRLF.5-1-22000-1335.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: ansurfen.yock
PackageVersion: 0.0.18
PackageLocale: en-US
Publisher: ansurfen
PublisherUrl: https://github.com/Ansurfen
# PublisherSupportUrl:
# PrivacyUrl:
Author: ansurfen
PackageName: yock
PackageUrl: https://github.com/Ansurfen/yock
License: MIT
LicenseUrl: https://github.com/Ansurfen/yock/blob/main/LICENSE
Copyright: Copyright (c) 2023 Ansurfen
CopyrightUrl: https://github.com/Ansurfen/yock/blob/main/LICENSE
ShortDescription: Yock is a solution of cross platform to compose distributed build stream.
Description: Yock is a solution of cross platform to compose distributed build stream.
# Moniker:
Tags:
- build-tool
- distributed-systems
- lua
- package-manager
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.4.0
